### PR TITLE
install-build-deps: Replaced echo with printf and provided wrappers

### PR DESCRIPTION
**Pull request by Kreyren**
echo is non-standard on darwin so printf is better option to be used.

Originally i wanted to fix the code-quality issues, but i gave up on it so providing only this contribution.

Willing to rewrite the script assuming full abstract provided.

Signed-off-by: Jacob Hrbek <kreyren@rixotstudio.cz>

### CODE REVIEW

**Comment by Kreyren** [comment]
Furthermore i consider current install-build-deps being a shell malware for the terrible code quality and manipulation with gpg command and so it should not be used on production system and by end-users concerned by security.

**Comment by kiwibrowser** [comment]
This is the source of the malware :D
https://chromium.googlesource.com/chromium/src/+/master/build/install-build-deps.sh

Maybe it's worth reporting it to http://bugs.chromium.org/ upstream ?

**Comment by kiwibrowser** [comment]
Wow, I saw you did actually quite a few changes.

I will let you submit the CL / PR to Chromium, if you need assistance with doing so, I can do it, but I think you prefer to have your name attached to it.

Let me know what you prefer, otherwise I can merge only in Kiwi

**Comment by Kreyren** [comment]
I try to merge in chromium then thanks for info

**Pull request closed without merging**
