### PR TITLE
Cancel old build as it's waste of processing power and potentially could cause issues.

### PR DESCRIPTION
**Pull request by budgidiere**
To get this to work you have to do the following:

Visit https://github.com/settings/tokens to generate a token with public_repo scope (or full repo scope for private repos).

Visit https://github.com/:org/:repo/settings/secrets to add a secret called GH_ACCESS_TOKEN with the token as the value.

Visit https://api.github.com/repos/:org/:repo/actions/workflows to find the Workflow ID you wish to auto-cancel.

### CODE REVIEW

**Comment by kiwibrowser** [comment]
Checking what are the risks to share GH_ACCESS_TOKEN to a third-party / non-official action

**Comment by kiwibrowser** [comment]
I read and the actions make reference to a specific tag, tags can be deleted and recreated which eventually could cause the private key to be stolen.

There is an easy solution to that though, it's simply to fork the repo, so I'll check that.

**Comment by SuperSandro2000** [comment]
I think canceling CI makes only sense in PRs or non master branches. If you cancel jobs on master they will be marked with an X and you think that CI is broken. Also this makes it harder to find out since when the pipeline is broken.

**Comment by kiwibrowser** [comment]
Hello,

I think for now it's more simple to build everything, if later the number of parallel builds become an issue due to GitHub quotas then I will refer back to this PR.

Thanks again for submitting it, I will close it for now until/if we face the situation.

**Pull request closed without merging**
